spring:
  jpa:
    database: DERBY
    show-sql: true
    hibernate:
      ddl-auto:
        create-drop
  datasource:
    platform: derby
    url: jdbc:derby:guitarshop;create=true
    username: sa
    password:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      schema: SA